root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./"
bin = "tmp/app"
full_bin = "APP_ENV=dev ./tmp/app"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", ".git"]
exclude_regex = ["_test.go"]
delay = 200

[log]
time = true

[color]
app            = "green"
build          = "yellow"
main           = "magenta"
runner         = "cyan"
watcher        = "blue"

[misc]
clean_on_exit = true
